# server/configs/config.prod.yaml

# 服务器配置
server:
  port: 80 # 生产环境通常使用 80 或 443 端口

# MySQL 数据库配置
mysql:
  host: "prod.db.host.com" # 生产数据库地址
  port: 3306
  user: "prod_user"
  password: "!!EXTREMELY_STRONG_AND_SECRET_PASSWORD!!" # 必须是高强度密码，并从安全的地方（如环境变量、配置中心）加载
  dbname: "gin_vue_prod" # 生产数据库
  config: "charset=utf8mb4&parseTime=True&loc=Local"

# JWT 配置
jwt:
  issuer: "gin-vue-prod"
  secret: "!!USE_A_VERY_LONG_AND_RANDOMLY_GENERATED_SECRET_KEY!!" # 必须是随机生成的长密钥
  expire: 3600 # 生产环境建议使用较短的 Token 有效期
